import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. Import your new component
import FloatingMenu from "./components/FloatingMenu"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* 2. Add the component here so it renders on every page */}
        <FloatingMenu />
        
      </body>
    </html>
  );
}